#
# Copyright Pravega Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 
version: '2'
services:
  zookeeper:
    image: zookeeper:3.6.1
    ports:
      - "2181:2181"

  bookie1:
    image: pravega/bookkeeper
    ports:
      - "3181:3181"
    environment:
      ZK_URL: zookeeper:2181
      bookiePort: 3181
    links:
      - zookeeper

  bookie2:
      image: pravega/bookkeeper
      ports:
        - "3182:3182"
      environment:
        ZK_URL: zookeeper:2181
        bookiePort: 3182
      links:
        - zookeeper

  bookie3:
      image: pravega/bookkeeper
      ports:
        - "3183:3183"
      environment:
        ZK_URL: zookeeper:2181
        bookiePort: 3183
      links:
        - zookeeper

  controller:
    image: pravega/pravega
    ports:
      - "9090:9090"
      - "10080:10080"
    command: controller
    environment:
      WAIT_FOR: zookeeper:2181
      ZK_URL: zookeeper:2181
      REST_SERVER_PORT: 10080
      JAVA_OPTS: |
        -Dcontroller.service.rpc.listener.port=9090
        -Xmx512m
        -XX:OnError="kill -9 p%"
        -XX:+ExitOnOutOfMemoryError
        -XX:+CrashOnOutOfMemoryError
        -XX:+HeapDumpOnOutOfMemoryError
      SERVICE_HOST_IP: segmentstore
    links:
      - zookeeper

  segmentstore:
    image: pravega/pravega
    ports:
      - "12345:12345"
    command: segmentstore
    restart: always
    privileged: true
    environment:
      WAIT_FOR: bookie1:3181,bookie2:3182,bookie3:3183
      TIER2_STORAGE: "EXTENDEDS3"
      EXTENDEDS3_ACCESS_KEY_ID: U3VNT902CYU0WB5CGRLY
      EXTENDEDS3_BUCKET: pravega-test
      EXTENDEDS3_SECRET_KEY: jSTbyD9g58ph_zxQ1YP_OUqk_Cd9CT9j41NH43s
      EXTENDEDS3_URI: s3-production.kionetworks.es:20016
      ZK_URL: zookeeper:2181
      CONTROLLER_URL: tcp://172.16.3.10:9090
      JAVA_OPTS: |
        -Dpravegaservice.service.published.host.nameOrIp=172.16.3.10
        -Dbookkeeper.ensemble.size=2
        -Dbookkeeper.ack.quorum.size=2
        -Dbookkeeper.write.quorum.size=2
        -Xmx900m
        -XX:OnError="kill -9 p%"
        -XX:+ExitOnOutOfMemoryError
        -XX:+CrashOnOutOfMemoryError
        -XX:+HeapDumpOnOutOfMemoryError
    links:
      - zookeeper
      - bookie1
      - bookie2
      - bookie3

