#
# Copyright Pravega Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
version: '2'
volumes:
  nfs:
    driver: local
    driver_opts:
      type: nfs
      o: addr=127.0.0.1,nolock,soft,rw
      device: ":/mnt/sdb/pravega-data"
services:
  zookeeper:
    image: zookeeper:3.6.1
    ports:
      - "2181:2181"

  bookie:
    image: pravega/bookkeeper
    ports:
      - "3181:3181"
    restart: always
    environment:
      ZK_URL: zookeeper:2181
      bookiePort: 3181
    links:
      - zookeeper

  controller:
    image: pravega/pravega
    ports:
      - "9090:9090"
      - "10080:10080"
    command: controller
    environment:
      WAIT_FOR: zookeeper:2181
      ZK_URL: zookeeper:2181
      REST_SERVER_PORT: 10080
      JAVA_OPTS: |
        -Dcontroller.service.rpc.listener.port=9090
        -Xms1g
        -Xmx1g
        -XX:+ExitOnOutOfMemoryError
        -XX:+CrashOnOutOfMemoryError
        -XX:+HeapDumpOnOutOfMemoryError
        -XX:OnError="kill -9 p%"
      SERVICE_HOST_IP: segmentstore
    links:
      - zookeeper

  segmentstore:
    image: pravega/pravega
    ports:
      - "12345:12345"
    command: segmentstore
    volumes:
      - nfs:/nfs/
    environment:
      WAIT_FOR: bookie:3181
      TIER2_STORAGE: "FILESYSTEM"
      NFS_MOUNT: /nfs
      ZK_URL: zookeeper:2181
      CONTROLLER_URL: tcp://${HOST_IP}:9090
      JAVA_OPTS: | 
        -Dpravegaservice.service.published.host.nameOrIp=${HOST_IP}
        -Dbookkeeper.ensemble.size=1
        -Dbookkeeper.ack.quorum.size=1
        -Dbookkeeper.write.quorum.size=1
        -Xms4g
        -Xmx4g
        -XX:MaxDirectMemorySize=26g
        -Dpravegaservice.cache.size.max=23622320128
        -XX:OnError="kill -9 p%"
        -XX:+ExitOnOutOfMemoryError
        -XX:+CrashOnOutOfMemoryError
        -XX:+HeapDumpOnOutOfMemoryError
        -XX:+UseContainerSupport
        -XX:+PrintExtendedThreadInfo
    links:
      - zookeeper
      - bookie

